### ISSUE TITLE
pdf下载后发现边距过大

### ISSUE THREAD

**Issue by arcosx** [Yohoa/Download-Scanned-Book-from-the-Library-of-NUAA#1]
在下载完pdf后发现边距过大。
图一：图书馆正常的浏览电子资源
![](http://p0xjmrizh.bkt.clouddn.com/15287706473935.jpg)

图二：下载后的电子资源
![](http://p0xjmrizh.bkt.clouddn.com/15287706670482.jpg)

**Comment by Yohoa** [comment]
Acknowledged，请看一下Image2PDF.py 第200行的ratio，试一试乘上一个系数能否带来不同。

这个现象可以在我这里复现，但是因为没有影响使用（我的阅读器是MarginNote，它可以修改阅读时的边距），所以没有深究。
